{
    "findings": [
        {
            "text": "The vulnerable class django.http.FileResponse is instantiated with the attribute as_attachment set to True, The vulnerable function django.http.FileResponse.set_headers is called with external input when filename argument is not provided in django.http.FileResponse instantiation",
            "evidence": [
                {
                    "cell_type": "values_only",
                    "text": "",
                    "rows": [
                        [
                            "gadgets_scanners/applicable/tests/data/python/CVE_2022_36359/applicable/con3.py",
                            "FileResponse(as_attachment=True)",
                            "8",
                            "The vulnerable class django.http.FileResponse is instantiated with the attribute as_attachment set to True"
                        ],
                        [
                            "gadgets_scanners/applicable/tests/data/python/CVE_2022_36359/applicable/con3.py",
                            "FileResponse(as_attachment=True)",
                            "8",
                            "The vulnerable function django.http.FileResponse.set_headers is called with external input when filename argument is not provided in django.http.FileResponse instantiation"
                        ]
                    ],
                    "column_names": [
                        "Path",
                        "Evidence",
                        "Line Number",
                        "Issue Found"
                    ]
                }
            ],
            "conclusion": "negative"
        }
    ],
    "conclusion": "negative"
}